#!/bin/bash
apt-get install -y build-essential libbz2-dev zlib1g-dev

#scamper
wget https://www.caida.org/tools/measurement/scamper/code/scamper-cvs-20141211e.tar.gz
tar zxvf scamper-cvs-20141211e.tar.gz
cd scamper-cvs-20141211e/
./configure
make && make install
cd ../
rm scamper-cvs-20141211e.tar.gz

test ! -z "$(cat /etc/ld.so.conf | grep 'include /usr/local/lib')" && echo 'include /usr/local/lib' >>/etc/ld.so.conf
ldconfig

#python2.7
wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
tar zxvf Python-2.7.12.tgz
cd Python-2.7.12
./configure
make && make install
cd ../
rm Python-2.7.12.tgz
