{
  "source#1":{
    "username":"illuminati_anonymous_guy",
    "password":"illuminati_confirmed"
  },
  "source#2":{
    "username":"mlg_noscoper_sergant_dude",
    "password":"ma_hope_will_never_die"
  }
}
